--- # My Loops Playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
         - name: add lists of users in my node 
           user: name='{{item}}' state=present
           with_items:
                   - Abdul
                   - Basit
                   - Ihsan
                   - Sanam 
