--- # My First test playbook Abdul Basit
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
         - name: Install HTTPD on centos 7
           action: yum name=httpd state=installed
